# Generated by Django 3.1.6 on 2021-02-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20210213_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['date', 'id']},
        ),
    ]
