# Generated by Django 3.1.7 on 2021-04-11 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cart',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator('^\\d+$/', message='Строка должна состоять только из цифр')]),
        ),
    ]
